#!/bin/bash

NAME=$1
P=$$
LANG=C

echo $NAME | egrep -q '^[a-z]+[0-9]{2}$' || (echo Usage: $(basename $0) vmNN ; kill -9 $P )

if [[ $2 != "--now" ]] ; then
  vme $NAME > /dev/null

  echo "GOING TO DESTROY $NAME"
  echo "ctrl-c now!"
  sleep 5
else
  vme $NAME --now > /dev/null 2>&1
fi

virsh undefine $NAME > /dev/null
rm -f /srv/vm/datastores/vms/$NAME.qcow2

