#!/bin/bash
# DESC: show all vms across multiple kvm servers
# Author: chris@bitbull.ch
# Edit: tcan-ch

# Copyright (c) Chris Ruettimann <chris@bitbull.ch>

# This software is licensed to you under the GNU General Public License.
# There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/gpl.txt

bold=$(tput bold)
reset=$(tput sgr0)
divider========================================
divider=$divider$divider


echo "$bold"
echo "$(uname -n | tr 'a-z' 'A-Z') ->"
echo "      commited mem (running VMs): $(virsh list --name | while read vm; do virsh domstats $vm | grep balloon.maximum ; done | cut -d= -f2 | awk '{s+=$0$
echo "      used mem (running VMs): $(virsh list --name | while read vm; do virsh domstats $vm | grep balloon.current ; done | cut -d= -f2 | awk '{s+=$0} EN$
echo "      virtHost free mem: $(( $(free -t | grep ^Mem: | awk '{print $7}') / 1024 /1024 )) GB"
echo " "

#virsh list --all --title | sed 's/^/     /g'



printf "%-5s %-25s %-10s %-5s %-15s %-s" "Id" "Name" "State" "vCPUs" "Memory" "Description"
echo ""
echo $divider

for VM in `virsh list --all | awk '{print $2}' | tail -n+3 | head -n-1`
do
    ID="$(virsh dominfo $VM | grep Id | cut -f 2- -d ":" | awk '{$1=$1};1')"
    STATE="$(virsh dominfo $VM | grep State | cut -f 2- -d ":" | awk '{$1=$1};1')"
    CPU="$(virsh dominfo $VM | grep "CPU(s)" | cut -f 2- -d ":" | awk '{$1=$1};1')"
    MEMORY="$(virsh dominfo $VM | grep "Max memory" | cut -f 2- -d ":" | awk '{$1=$1};1')"
    DESCR="$(virsh desc --domain $VM)"

    printf "%-5s %-25s %-10s %-5s %-15s %-s" "$ID" "$VM" "$STATE" "$CPU" "$MEMORY" "$DESCR"
    echo ""
done


echo $reset
